name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repo
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Google Cloud authentication
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    # Step 3: Configure GCP project
    - name: Configure Google Cloud project
      run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    # Step 4: Deploy to Cloud Run
    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: note-api-${{ secrets.ORG_NAME }}  # Replace with your org name
        image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/note-api:${{ github.sha }}
        region: us-central1
        env_vars: BACKEND=memory

    # Step 5: Post-deployment steps (optional)
    - name: Verify deployment
      run: curl https://note-api-${{ secrets.ORG_NAME }}.run.app