name: Docker Push
run-name: Pushing a docker image to the GitHub registry
env:
  DOTNET_VERSION: '6.0.x'

on:
  push:
    branches: [main, docker]
  workflow_dispatch:

jobs:
  push-store-image:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4  # Use specific version for stability

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3  # Latest version of login-action
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push    
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/hs-heilbronn-devsecops-group-one/note-api:latest
